.\bin\Debug\net6.0\rsdr.exe "=++."
.\bin\Debug\net6.0\rsdr.exe "=+++."
.\bin\Debug\net6.0\rsdr.exe "=-+."
.\bin\Debug\net6.0\rsdr.exe "=+-+-."
.\bin\Debug\net6.0\rsdr.exe "=+-+-=++."
.\bin\Debug\net6.0\rsdr.exe "=+-+-=++>=+."
.\bin\Debug\net6.0\rsdr.exe "=+-+-=++>=+;."
.\bin\Debug\net6.0\rsdr.exe "=++>=+++;.>."
.\bin\Debug\net6.0\rsdr.exe "=++>+++;.>."
.\bin\Debug\net6.0\rsdr.exe "=+>" "=++>" "=+++" ";.>.>."
.\bin\Debug\net6.0\rsdr.exe "=+>" "++>" "=+++" ";.>.>."
.\bin\Debug\net6.0\rsdr.exe "=+*****."
.\bin\Debug\net6.0\rsdr.exe "=++++/."